#!/usr/bin/env python3
"""Generate sql/_idmap_lookup.sql and rendered export SQL from config JSON."""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "config"
SQL_DIR = ROOT / "sql"
TEMPLATE_DIR = SQL_DIR / "templates"


def sql_str(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "\\'")


def struct_rows(pairs: list[tuple[str, str]], fields: tuple[str, str]) -> str:
    if not pairs:
        return f"SELECT * FROM UNNEST(ARRAY<STRUCT<{fields[0]} STRING, {fields[1]} STRING>>[])"
    lines = ",\n    ".join(
        f"STRUCT('{sql_str(k)}' AS {fields[0]}, '{sql_str(v)}' AS {fields[1]})" for k, v in pairs
    )
    return f"SELECT * FROM UNNEST([\n    {lines}\n  ])"


def render_idmap_fragment(idmap: dict, sa_names: dict) -> str:
    aliases = struct_rows(list(idmap["aliases"].items()), ("alias", "person"))
    emails = struct_rows(list(idmap["emails"].items()), ("email", "person"))
    sa_map = struct_rows(list(sa_names.items()), ("email", "person"))

    return f"""-- Generated by scripts/render_idmap_sql.py — do not edit by hand.

alias_map AS (
  {aliases}
),

email_map AS (
  {emails}
),

sa_map AS (
  {sa_map}
)"""


def render_template(name: str, fragment: str) -> str:
    template = (TEMPLATE_DIR / name).read_text()
    return template.replace("{{IDMAP_LOOKUP}}", fragment)


def main() -> None:
    idmap = json.loads((CONFIG / "idmap.json").read_text())
    sa_names = json.loads((CONFIG / "sa_names.json").read_text())
    fragment = render_idmap_fragment(idmap, sa_names)

    lookup_path = SQL_DIR / "_idmap_lookup.sql"
    lookup_path.write_text(fragment + "\n")

    for template_name, out_name in (
        ("export_aggregated.sql.template", "export_aggregated.sql"),
        ("export_incremental.sql.template", "export_incremental.sql"),
    ):
        out_path = SQL_DIR / out_name
        out_path.write_text(render_template(template_name, fragment))

    print(f"Wrote {lookup_path}")
    print(f"Wrote {SQL_DIR / 'export_aggregated.sql'}")
    print(f"Wrote {SQL_DIR / 'export_incremental.sql'}")


if __name__ == "__main__":
    main()
