-- Generated by scripts/render_idmap_sql.py — do not edit by hand.

alias_map AS (
  SELECT * FROM UNNEST([
    STRUCT('venkatesh' AS alias, 'Venkatesh' AS person),
    STRUCT('yasho' AS alias, 'Yashovardhan' AS person),
    STRUCT('varanasi' AS alias, 'Aditya Varanasi' AS person),
    STRUCT('santoryu_zunder' AS alias, 'Aditya Zunder' AS person),
    STRUCT('devanshi' AS alias, 'Devanshi' AS person),
    STRUCT('devansh' AS alias, 'Devansh' AS person),
    STRUCT('devs' AS alias, 'Sourav' AS person),
    STRUCT('sourav' AS alias, 'Sourav' AS person),
    STRUCT('tanmay' AS alias, 'Tanmay' AS person),
    STRUCT('prasannajeet' AS alias, 'Prasannajeet' AS person),
    STRUCT('shibam' AS alias, 'Shibam' AS person),
    STRUCT('soham' AS alias, 'Soham' AS person),
    STRUCT('spoorthi' AS alias, 'Spoorthi' AS person),
    STRUCT('ankush' AS alias, 'Ankush' AS person),
    STRUCT('harkeerat' AS alias, 'Harkeerat' AS person),
    STRUCT('avipsa' AS alias, 'Avipsa' AS person),
    STRUCT('shugal' AS alias, 'Shugal' AS person)
  ])
),

email_map AS (
  SELECT * FROM UNNEST([
    STRUCT('venkatesh@hitwicket.com' AS email, 'Venkatesh' AS person),
    STRUCT('yashovardhan@hitwicket.com' AS email, 'Yashovardhan' AS person),
    STRUCT('aditya.varanasi@hitwicket.com' AS email, 'Aditya Varanasi' AS person),
    STRUCT('aditya.zunder@hitwicket.com' AS email, 'Aditya Zunder' AS person),
    STRUCT('devanshi@hitwicket.com' AS email, 'Devanshi' AS person),
    STRUCT('devansh@hitwicket.com' AS email, 'Devansh' AS person),
    STRUCT('sourav.s@hitwicket.com' AS email, 'Sourav' AS person),
    STRUCT('tanmay@hitwicket.com' AS email, 'Tanmay' AS person),
    STRUCT('prasannajeet@hitwicket.com' AS email, 'Prasannajeet' AS person),
    STRUCT('shibam@hitwicket.com' AS email, 'Shibam' AS person),
    STRUCT('soham@hitwicket.com' AS email, 'Soham' AS person),
    STRUCT('spoorthi@hitwicket.com' AS email, 'Spoorthi' AS person),
    STRUCT('ankush@hitwicket.com' AS email, 'Ankush' AS person),
    STRUCT('mustafa@hitwicket.com' AS email, 'Mustafa' AS person),
    STRUCT('aritra@hitwicket.com' AS email, 'Aritra' AS person),
    STRUCT('arsalaan@hitwicket.com' AS email, 'Arsalaan' AS person),
    STRUCT('asmi@hitwicket.com' AS email, 'Asmi' AS person),
    STRUCT('fayas@hitwicket.com' AS email, 'Fayas' AS person),
    STRUCT('rohit@hitwicket.com' AS email, 'Rohit' AS person),
    STRUCT('kiran@hitwicket.com' AS email, 'Kiran' AS person),
    STRUCT('anush@hitwicket.com' AS email, 'Anush' AS person),
    STRUCT('arjun@hitwicket.com' AS email, 'Arjun' AS person),
    STRUCT('keerti@hitwicket.com' AS email, 'Keerti' AS person),
    STRUCT('leetanshi@hitwicket.com' AS email, 'Leetanshi' AS person)
  ])
),

sa_map AS (
  SELECT * FROM UNNEST([
    STRUCT('bigquery-admin@hitwicketsuperstars.iam.gserviceaccount.com' AS email, 'SA: bigquery-admin' AS person),
    STRUCT('firebase-measurement@system.gserviceaccount.com' AS email, 'SA: firebase-measurement' AS person),
    STRUCT('reports-sa@hitwicketsuperstars.iam.gserviceaccount.com' AS email, 'SA: reports-sa' AS person),
    STRUCT('service-352216829522@gcp-sa-bigquerydatatransfer.iam.gserviceaccount.com' AS email, 'SA: data-transfer' AS person),
    STRUCT('352216829522-compute@developer.gserviceaccount.com' AS email, 'SA: compute' AS person),
    STRUCT('service-352216829522@gcp-sa-connectedsheets.iam.gserviceaccount.com' AS email, 'SA: connected-sheets' AS person)
  ])
)
