-- Reference template: incremental aggregated payload (edit since_date before each run).
-- Regenerate: python scripts/render_idmap_sql.py

DECLARE since_date DATE DEFAULT DATE '2026-06-23';  -- day after meta.last_data_date
DECLARE end_date DATE DEFAULT CURRENT_DATE('Asia/Kolkata');

WITH
-- Generated by scripts/render_idmap_sql.py — do not edit by hand.

alias_map AS (
  SELECT * FROM UNNEST([
    STRUCT('venkatesh' AS alias, 'Venkatesh' AS person),
    STRUCT('yasho' AS alias, 'Yashovardhan' AS person),
    STRUCT('varanasi' AS alias, 'Aditya Varanasi' AS person),
    STRUCT('santoryu_zunder' AS alias, 'Aditya Zunder' AS person),
    STRUCT('devanshi' AS alias, 'Devanshi' AS person),
    STRUCT('devansh' AS alias, 'Devansh' AS person),
    STRUCT('devs' AS alias, 'Sourav' AS person),
    STRUCT('sourav' AS alias, 'Sourav' AS person),
    STRUCT('tanmay' AS alias, 'Tanmay' AS person),
    STRUCT('prasannajeet' AS alias, 'Prasannajeet' AS person),
    STRUCT('shibam' AS alias, 'Shibam' AS person),
    STRUCT('soham' AS alias, 'Soham' AS person),
    STRUCT('spoorthi' AS alias, 'Spoorthi' AS person),
    STRUCT('ankush' AS alias, 'Ankush' AS person),
    STRUCT('harkeerat' AS alias, 'Harkeerat' AS person),
    STRUCT('avipsa' AS alias, 'Avipsa' AS person),
    STRUCT('shugal' AS alias, 'Shugal' AS person)
  ])
),

email_map AS (
  SELECT * FROM UNNEST([
    STRUCT('venkatesh@hitwicket.com' AS email, 'Venkatesh' AS person),
    STRUCT('yashovardhan@hitwicket.com' AS email, 'Yashovardhan' AS person),
    STRUCT('aditya.varanasi@hitwicket.com' AS email, 'Aditya Varanasi' AS person),
    STRUCT('aditya.zunder@hitwicket.com' AS email, 'Aditya Zunder' AS person),
    STRUCT('devanshi@hitwicket.com' AS email, 'Devanshi' AS person),
    STRUCT('devansh@hitwicket.com' AS email, 'Devansh' AS person),
    STRUCT('sourav.s@hitwicket.com' AS email, 'Sourav' AS person),
    STRUCT('tanmay@hitwicket.com' AS email, 'Tanmay' AS person),
    STRUCT('prasannajeet@hitwicket.com' AS email, 'Prasannajeet' AS person),
    STRUCT('shibam@hitwicket.com' AS email, 'Shibam' AS person),
    STRUCT('soham@hitwicket.com' AS email, 'Soham' AS person),
    STRUCT('spoorthi@hitwicket.com' AS email, 'Spoorthi' AS person),
    STRUCT('ankush@hitwicket.com' AS email, 'Ankush' AS person),
    STRUCT('mustafa@hitwicket.com' AS email, 'Mustafa' AS person),
    STRUCT('aritra@hitwicket.com' AS email, 'Aritra' AS person),
    STRUCT('arsalaan@hitwicket.com' AS email, 'Arsalaan' AS person),
    STRUCT('asmi@hitwicket.com' AS email, 'Asmi' AS person),
    STRUCT('fayas@hitwicket.com' AS email, 'Fayas' AS person),
    STRUCT('rohit@hitwicket.com' AS email, 'Rohit' AS person),
    STRUCT('kiran@hitwicket.com' AS email, 'Kiran' AS person),
    STRUCT('anush@hitwicket.com' AS email, 'Anush' AS person),
    STRUCT('arjun@hitwicket.com' AS email, 'Arjun' AS person),
    STRUCT('keerti@hitwicket.com' AS email, 'Keerti' AS person),
    STRUCT('leetanshi@hitwicket.com' AS email, 'Leetanshi' AS person)
  ])
),

sa_map AS (
  SELECT * FROM UNNEST([
    STRUCT('bigquery-admin@hitwicketsuperstars.iam.gserviceaccount.com' AS email, 'SA: bigquery-admin' AS person),
    STRUCT('firebase-measurement@system.gserviceaccount.com' AS email, 'SA: firebase-measurement' AS person),
    STRUCT('reports-sa@hitwicketsuperstars.iam.gserviceaccount.com' AS email, 'SA: reports-sa' AS person),
    STRUCT('service-352216829522@gcp-sa-bigquerydatatransfer.iam.gserviceaccount.com' AS email, 'SA: data-transfer' AS person),
    STRUCT('352216829522-compute@developer.gserviceaccount.com' AS email, 'SA: compute' AS person),
    STRUCT('service-352216829522@gcp-sa-connectedsheets.iam.gserviceaccount.com' AS email, 'SA: connected-sheets' AS person)
  ])
),

jobs AS (
  SELECT
    job_id,
    user_email,
    COALESCE(
      (SELECT value FROM UNNEST(labels) WHERE key = 'requestor'),
      (SELECT value FROM UNNEST(labels) WHERE key = 'queried_by'),
      user_email
    ) AS query_requested_by,
    DATE(creation_time, 'Asia/Kolkata') AS date,
    EXTRACT(HOUR FROM TIME(creation_time, 'Asia/Kolkata')) AS hour,
    ROUND(total_bytes_processed / POW(1024, 3), 2) AS gb
  FROM
    `region-us`.INFORMATION_SCHEMA.JOBS_BY_PROJECT
  WHERE
    DATE(creation_time, 'Asia/Kolkata') BETWEEN since_date AND end_date
    AND job_type = 'QUERY'
    AND state = 'DONE'
    AND total_bytes_processed > 0
),

resolved AS (
  SELECT
    j.*,
    COALESCE(
      (SELECT person FROM sa_map WHERE email = j.query_requested_by LIMIT 1),
      IF(
        j.query_requested_by = 'looker_studio',
        (SELECT person FROM email_map WHERE LOWER(email) = LOWER(j.user_email) LIMIT 1),
        NULL
      ),
      IF(
        CONTAINS_SUBSTR(j.query_requested_by, 'gserviceaccount.com'),
        COALESCE(
          (SELECT person FROM sa_map WHERE email = j.query_requested_by LIMIT 1),
          CONCAT('SA: ', SPLIT(j.query_requested_by, '@')[SAFE_OFFSET(0)])
        ),
        NULL
      ),
      IF(
        CONTAINS_SUBSTR(j.query_requested_by, '@hitwicket.com'),
        (SELECT person FROM email_map WHERE LOWER(email) = LOWER(j.query_requested_by) LIMIT 1),
        NULL
      ),
      (SELECT person FROM alias_map WHERE LOWER(alias) = LOWER(j.query_requested_by) LIMIT 1),
      (SELECT person FROM email_map WHERE LOWER(email) = LOWER(j.user_email) LIMIT 1)
    ) AS person,
    CASE
      WHEN j.query_requested_by = 'looker_studio' THEN 0
      WHEN CONTAINS_SUBSTR(j.query_requested_by, '@hitwicket.com') THEN 1
      WHEN CONTAINS_SUBSTR(j.query_requested_by, 'gserviceaccount.com') THEN 3
      ELSE 2
    END AS source_idx,
    CASE
      WHEN j.query_requested_by = 'looker_studio' THEN 'Looker'
      WHEN CONTAINS_SUBSTR(j.query_requested_by, '@hitwicket.com') THEN 'Console'
      WHEN CONTAINS_SUBSTR(j.query_requested_by, 'gserviceaccount.com') THEN 'SA-Cron'
      ELSE 'Script'
    END AS src_label
  FROM
    jobs AS j
),

mapped AS (
  SELECT * FROM resolved WHERE person IS NOT NULL
),

unmapped AS (
  SELECT
    query_requested_by AS key,
    COUNT(*) AS count
  FROM
    resolved
  WHERE
    person IS NULL
  GROUP BY
    1
),

daily AS (
  SELECT
    CAST(date AS STRING) AS date,
    person,
    source_idx AS source,
    ROUND(SUM(gb), 2) AS gb,
    COUNT(*) AS q
  FROM
    mapped
  GROUP BY
    1, 2, 3
),

hourly AS (
  SELECT
    CAST(date AS STRING) AS date,
    person,
    hour,
    ROUND(SUM(gb), 2) AS gb
  FROM
    mapped
  GROUP BY
    1, 2, 3
),

ranked_jobs AS (
  SELECT
    job_id,
    CAST(date AS STRING) AS date,
    person,
    src_label AS src,
    gb,
    ROW_NUMBER() OVER (ORDER BY gb DESC) AS rn
  FROM
    mapped
),

top_jobs AS (
  SELECT job_id, date, person, src, gb FROM ranked_jobs WHERE rn <= 100
)

SELECT
  TO_JSON_STRING(
    STRUCT(
      CAST(since_date AS STRING) AS window_start,
      CAST(end_date AS STRING) AS window_end,
      (SELECT ARRAY_AGG(STRUCT(date, person, source, gb, q)) FROM daily) AS daily,
      (SELECT ARRAY_AGG(STRUCT(date, person, hour, gb)) FROM hourly) AS hourly,
      (SELECT ARRAY_AGG(STRUCT(job_id, date, person, src, gb)) FROM top_jobs) AS top_jobs,
      (SELECT ARRAY_AGG(STRUCT(key, count)) FROM unmapped) AS unmapped
    )
  ) AS payload
FROM
  (SELECT 1);
